version: "1.1"
pipeline:
  name: bodywork-ml-pipeline-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: stage_1_train_model >> stage_2_scoring_service
stages:
  stage_1_train_model:
    executable_module_path: pipeline/train_model.py
    requirements:
      - pandas==2.2.3
      - scikit-learn==1.6.1
    cpu_request: 0.5
    memory_request_mb: 100
    batch:
      max_completion_time_seconds: 60
      retries: 2
  stage_2_scoring_service:
    executable_module_path: pipeline/serve_model.py
    requirements:
      - Flask==3.1.0
      - numpy==2.0.2
      - pandas==2.2.3
      - scikit-learn==1.6.1
    cpu_request: 0.25
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 60
      replicas: 1
      port: 5000
      ingress: true
logging:
  log_level: INFO